### ISSUE TITLE
CreateListFromArrayLike on non-object error

### ISSUE THREAD

**Issue by mrvini** [RIAEvangelist/event-pubsub#10]
while broadcasting to all events on *, this error came up, also similar to #7

```bash
/opt/connector/node_modules/event-pubsub/es6.js:79
            handler.apply(this, type, args);
                    ^

TypeError: CreateListFromArrayLike called on non-object
    at Client.emit$ (/opt/connector/node_modules/event-pubsub/es6.js:79:21)
    at Client.emit (/opt/connector/node_modules/event-pubsub/es6.js:58:25)
    at Socket.connectionMade (/opt/connector/node_modules/node-ipc/dao/client.js:140:20)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1067:10)
```

this could be fixed with 

in es6.js replace line 78
```javascript
handler.apply(this, type, args);
```
with 
```javascript
args.unshift(type)
handler.apply(this, args);
```

**Comment by RIAEvangelist** [comment]
`args.unshift(type)` is too slow. switching to `.call`

**Comment by RIAEvangelist** [comment]
btw, thats what the ES5 module does.
